### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by Skeyelab** [xdavidhu/mitmAP#1]
I am unsure if this is doing anything.  I set it up on my raspberry pi, and can use the new AP, but nothing appears in the log or in the console.  Am I missing something?

**Comment by xdavidhu** [comment]
If you are using SSLStrip, only POST requests will appear in the log & console.

Answer no when mitmAP asks for using sslstrip, and than select mitmproxy to view all of the http/https traffic.

**Comment by Skeyelab** [comment]
Thanks. Some basic usage instructions would be helpful.
