### ISSUE TITLE
Dnsmask : symbol 'nettle_hashes' had different size in shared object

### ISSUE THREAD

**Issue by vitteloil** [xdavidhu/mitmAP#11]
Hi,

mitmAP is not working for me. I guess that's because dnsmask shows this warning when starting:

Dnsmask : symbol 'nettle_hashes' had different size in shared object, consider re-linking.

Once everything is started, I can connect to the AP but can't browse anything (error in clients : domain names can't be resolved).

There is nothing in mitmap-sslstrip.log, and I don't have more log files.
I noticed this dnsmask issue appeared in other distros but I have the latest kali packages so I wonder, if that's the problem, do you also have this warning ?

If this warning is not important, is there a way to have more logs ?

Thanks

**Comment by Jheguy2** [comment]
I am experiencing the same error

**Comment by xdavidhu** [comment]
I done a little bit of research, and it's a bug in the new dnsmasq packages, but i don't think that it should effect mitmAP. If you are using sslstrip2, than dns2proxy is handling the DNS requests, so please try starting mitmAP/src/dns2proxy/dns2proxy.py with python 2 manually, and if it's crashing, please send it to me here.

**Comment by xdavidhu** [comment]
Closing this issue because of no response from OP.
