### ISSUE TITLE
Created AP not visible

### ISSUE THREAD

**Issue by risogolo** [xdavidhu/mitmAP#114]
Trying on Kali linux on RPI3, 2 wireless adapter option, seems to be like AP is not created or something, still not visible in available networks from different computer

**Comment by xdavidhu** [comment]
Hey,

The rpi version is for Raspbian on a Raspberry Pi, not for Kali.
Please try the main version which is made for Kali. (not sure if that works but there is no script yet specifically for Raspberry Pi Kali)

**Comment by risogolo** [comment]
To be more specific, I ran Kali version of script on Kali linux for RPI 3, everything seems to be fine, but it looks like AP is no created or something, can you please provide script also for Kali linux for RPI. thx

**Comment by risogolo** [comment]
it also does not work on the latest version of rasbian (sane behavior like on kali for rpi), on what version of raspbian is it supposed to work?

**Comment by risogolo** [comment]
so It works on kali for rpi, I just did not have wifi adapter supporting ap mode, my bad...
you can close it, it works now with new adapter

**Comment by xdavidhu** [comment]
Ah okey, yes, if your adapter can't support AP mode its unfortunately not going to work.

But happy to hear that its all good with the new card!
