### ISSUE TITLE
Please we need this for Raspberry Pi Kali

### ISSUE THREAD

**Issue by RoQuark** [xdavidhu/mitmAP#116]
I am shock of this new python script. I think its great because it combines sslstrip2 and dnsproxy and it makes it all automatically. I tried to run it on kali for Raspberry Pi, all two versions, but it doenst work. It would be great if you could fix it.

Congratulations for your work.

**Comment by xdavidhu** [comment]
Hey! I got my hands on a Raspberry Pi with Kali on it and I tried mitmAP on it. Despite some dependency install problems (what I fixed in the latest commits) it worked fine. Could you please try it out and see if it works? (the mitmAP.py, not the rpi version)

**Comment by RoQuark** [comment]
Heey! Just tested in Raspberry Pi 3 with Kali Linux and it works great. Great job David👏

**Comment by xdavidhu** [comment]
Thanks, happy it works!
