### ISSUE TITLE
AP Issue

### ISSUE THREAD

**Issue by beeprime** [xdavidhu/mitmAP#16]
I have applied the earlier fix but still no AP is coming up. Below is the o/p I am getting from my Kali VM

[I] Writing config file...
[I] Configuring AP interface...
[I] Applying iptables rules...
[?] Set speed limit for the clients? Y/n: n
[I] Skipping...
[?] Start WIRESHARK on wlan0? Y/n: n
[?] Capture packets to .pcap with TSHARK? (no gui needed) Y/n: n
[?] Spoof DNS manually? y/N: N
[I] Starting DNSMASQ server...
[I] Starting AP on wlan0 in screen terminal...
[I] Starting DRIFTNET...

TAIL started on /root/mitmAP/logs/mitmap-sslstrip.log...
Wait for output... (press 'CTRL + C' 2 times to stop)
HOST-s, POST requests and COOKIES will be shown.

[I] Restarting tail in 1 sec... (press 'CTRL + C' again to stop)

**Comment by xdavidhu** [comment]
Had you said "n" at the WPA password question?

**Comment by beeprime** [comment]
certainly and my hostapd is also the newest version.
Upon pressing CTRL+C, it tells that no session was found.
What should I do?

**Comment by beeprime** [comment]
Meanwhile, I installed it last friday and since then didn't clone your git repo. So if you did any modification in the mean time, it shouldn't be reflected in my case.
Secondly, I put "n" straight forward when the script asked whether I want to use WPA2 only to disable this WPA option as far as your earlier discussion is concerned , so WPA password question option didn't come.

**Comment by xdavidhu** [comment]
Can you send me please your /etc/hostapd.conf file?


Also start it manually with this command:
"sudo hostapd /etc/hostapd/hostapd.conf"
And send me the error what this gives as well.

**Comment by beeprime** [comment]
Below is error msg
# hostapd /etc/hostapd/hostapd.conf
Configuration file: /etc/hostapd/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

**Comment by beeprime** [comment]
content of hostapd.conf

interface=wlan0
driver=nl80211
ssid=TestingAP
hw_mode=g
channel=11
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0

**Comment by xdavidhu** [comment]
Its something to do with your virtual machine. If you are running this on a virtual machine, maybe you should consider trying on a booted kali (e.g. from usb), or use a usb wireless adapter and connect it properly vm.

What wireless card are you using? Maybe there is a problem with the drivers.

**Comment by beeprime** [comment]
I am using alpha card as wireless interface whereas ethernet the internet facing interface.

**Comment by xdavidhu** [comment]
Are you running it in a virtual machine, or you have kali fully booted?

**Comment by beeprime** [comment]
I am running it inside VM. But in case of fully booted Kali, the problem remains the same that no AP is coming up.

**Comment by xdavidhu** [comment]
Its possible that something is using the wireless card in the background. Try killing all of the wireless-type processes with airmon-ng, and  after it try running hostapd manually again.

1. `airmon-ng check kill`

2. `hostapd /etc/hostapd/hostapd.conf`

**Comment by beeprime** [comment]
I think its a bug of Kali :(

https://bugs.kali.org/view.php?id=3751

error I am getting

root@Attacker:~# hostapd /etc/hostapd/hostapd.conf
Configuration file: /etc/hostapd/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started

**Comment by xdavidhu** [comment]
@beeprime Is this bug fixed by now? Can you please try running mitmAP again after a full dist upgrade:

`sudo apt-get update && sudo apt-get dist-upgrade -y`

**Comment by xdavidhu** [comment]
Closing issue because of no reply from OP.

**Comment by derrabe** [comment]
FWIW I have exactly the same issues as the original poster - tried all the suggestions in this thread and none have worked.

**Comment by xdavidhu** [comment]
@derrabe Can you start hostapd manually?

`sudo hostapd /etc/hostapd/hostapd.conf'

**Comment by derrabe** [comment]
Hi,
Nope - I ran airmon-ng check kill first, then hostapd /etc/hostapd/hostapd.conf and got:

```
hostapd /etc/hostapd/hostapd.conf
Configuration file: /etc/hostapd/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started
```
Also, I ran apt-get update && apt-get dist-upgrade a couple of hours ago, so things should be up to date:

`Linux kali 4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux
`

When running mitmap.py, when it gets to the stage of:

```
[?] Please enter the name of your wireless interface (for the AP): wlan0
[?] Please enter the name of your internet connected interface: eth0
[I] Backing up NetworkManager.cfg...
[I] Editing NetworkManager.cfg...
[I] Restarting NetworkManager...
```

it seems to drop the wlan0 interface (i.e. its no longer visible from an ifconfig)

**Comment by xdavidhu** [comment]
Can you bring it back up and after it start hostapd?
`ifconfig wlan0 up`

Also what wifi card are you using? (model, manifacturer)

**Comment by derrabe** [comment]
That gave the same result.

The card is an Alfa AWUS036H. I also tried it with an Alfa AWUS036NEH and had the same result.
