### ISSUE TITLE
Installation freezing on RPi3

### ISSUE THREAD

**Issue by BannersSecret** [xdavidhu/mitmAP#19]
Hi,

I am running for the first time on an RPi3, choosing to install dependencies, but it then goes no further. 

Is there a debug mode or anything else I can try in order to provide more details for you? Appreciate this isn't much to go on!

Thanks

**Comment by BannersSecret** [comment]
Problem with my local router. Fixed. Apologies.

**Comment by xdavidhu** [comment]
No problem :)

Happy to hear that it works now!
