### ISSUE TITLE
NameError: name 'Y' is not defined

### ISSUE THREAD

**Issue by eehP** [xdavidhu/mitmAP#2]
`` File "mitmAP.py", line 12, in <module>``
     `` update = input("[?] Install/Update dependencies? Y/n: ") ``
      ``File` "<string>", line 1, in <module> ``
      `` NameError: name 'Y' is not defined``

Could u fix this issue pls ??

thanks

**Comment by xdavidhu** [comment]
Are you sure that you run it with python3?

**Comment by eehP** [comment]
Thanks
that why it doesn't work...
