### ISSUE TITLE
how can i make it run @ 5 GHz?

### ISSUE THREAD

**Issue by joepvand** [xdavidhu/mitmAP#20]
how can i make the AP run on 5 ghz?

**Comment by xdavidhu** [comment]
After creating a hostapd config file, open it manually (/etc/hostapd/hostapd.conf), and add this to the end of the file:
`hw_mode=g`
After this, change the channel to a 5GH one, for example 40:
`channel=40`

I'm not sure if it works on every wifi card, please try it and tell me if it is working or not.

**Comment by xdavidhu** [comment]
Closing the issue because of no response from OP.
