### ISSUE TITLE
Mutiple client connections

### ISSUE THREAD

**Issue by asorsb** [xdavidhu/mitmAP#23]
Great tool! I did think that SSLstrip no longer worked, but I see this is still effective against android ;-) my question is will mitmAP accept multiple client connetions?? I did try but noticed that when I had a device connected to the SSID no other devices would connect?

**Comment by hkessel1** [comment]
Mine could connect multiple devices, I think. I'm running it on Kali linux, raspberry pi. 

Also, how did you get sslstrip to work? I know that they made another SSLstrip as well. (SSLstrip 2)

**Comment by asorsb** [comment]
Hey hkessel1, sorry I did mean SSLstrip2, tested and working on Android 4.1 and 7.0! Just got mutiple clients to connect now so all good ! thanks!

**Comment by xdavidhu** [comment]
@asorsb Happy to hear that its working fine for you now.

@hkessel1 Yep, Im using LeonardoNve's SSLStrip2
