### ISSUE TITLE
Block https

### ISSUE THREAD

**Issue by marvinfisher9** [xdavidhu/mitmAP#27]
Tell me please.
I want to completely close the https access. For example, the sslstrip didn't work and the victim wasn't redirected to https. how to do it? 
p.s.: sorry for my English

**Comment by crypiehef** [comment]
Is the website your trying to sslstrip HSTS? If so, sslstrip will not work. Most sites are now going to HSTS. i.e. google.com <http://google.com/>, Facebook.com and a lot more.

Sslstrip newest version does support stripping HSTS to a degree but it’s still hit or miss. 

-Crypiehef

**Comment by marvinfisher9** [comment]
That's right, but I'm talking about something else. I need to prevent the victim from accessing the Internet if the sslstrip does not work.

**Comment by crypiehef** [comment]
You could set up an iptables rules to block port 445. 

iptables -A INPUT -p tcp --destination-port {445} -j DROP

**Comment by marvinfisher9** [comment]
Not working, victim have access to https.

**Comment by crypiehef** [comment]
Sorry. I put wrong port. 443.

**Comment by hkessel1** [comment]
I was gonna say @crypiehed.. lol

**Comment by xdavidhu** [comment]
Hey, @crypiehef is right but dont forget to run this command after the AP is started, since mitmAP is flushing the iptables rules on every start @marvinfisher9.

**Comment by marvinfisher9** [comment]
thx, but problem didn't dare((  From the very beginning I was sending close 443 ports. Even tried to enter into the script itself   

#IPTABLES
print("[I] Configuring AP interface...")
os.system("sudo ifconfig " + ap_iface + " up 10.0.0.1 netmask 255.255.255.0")
print("[I] Applying iptables rules...")
os.system("sudo iptables --flush")
os.system("sudo iptables --table nat --flush")
os.system("sudo iptables --delete-chain")
os.system("sudo iptables --table nat --delete-chain")
os.system("sudo iptables --table nat --append POSTROUTING --out-interface " + net_iface + " -j MASQUERADE")
os.system("sudo iptables --append FORWARD --in-interface " + ap_iface + " -j ACCEPT")
os.system("sudo iptables -A INPUT -p tcp --destination-port {445} -j DROP")
#/IPTABLES

Also tried as told @xdavidhu , doesn't work(

**Comment by crypiehef** [comment]
Did you change 445 in the script to 443? Your paste still shows 445.

**Comment by marvinfisher9** [comment]
> Did you change 445 in the script to 443? Your paste still shows 445.

yes

**Comment by crypiehef** [comment]
David may correct me if I’m wrong but you may have to specify the interface in the Iptables drop statement.

-Crypiehef

**Comment by marvinfisher9** [comment]
> David may correct me if I’m wrong but you may have to specify the interface in the Iptables drop statement.

sudo iptables -A INPUT -i wlan1 -p tcp --destination-port 443 -j DROP
doesn't work(

**Comment by crypiehef** [comment]
Sorry, I don’t have my kali box with me to test right now.. But is there a br-lan interface that comes up after running the mitmAP script? Try applying the rule to that interface if so.

**Comment by marvinfisher9** [comment]
Tried all the interfaces in turn (wlan1, ppp0, wwan0...). doesn't work

**Comment by marvinfisher9** [comment]
BR-Lan  -  doesn't appear

**Comment by xdavidhu** [comment]
@marvinfisher9 Try this rule:

`iptables -I INPUT 1 -p tcp -i <ap interface> --dport 443 -j DROP`

**Comment by marvinfisher9** [comment]
> @marvinfisher9 Try this rule:

> iptables -I INPUT 1 -p tcp -i <ap interface> --dport 443 -j DROP

Thank you, I'll try it tomorrow

**Comment by marvinfisher9** [comment]
@xdavidhu , Doesn't work, the victim still has access to https(

**Comment by marvinfisher9** [comment]
have you any ideas?

**Comment by marvinfisher9** [comment]
If anyone comes in handy


 proxy_if = "n"
    os.system("sudo iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 9000")
    os.system("sudo iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-port 53")
    os.system("sudo iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-port 53")
    os.system("sudo sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1")
    os.system("sudo iptables -t nat -A PREROUTING -p tcp --destination-port 443 -j REDIRECT --to-port 9000")
    os.system("sudo iptables -t nat -A PREROUTING -p udp --destination-port 443 -j REDIRECT --to-port 9000")
