### ISSUE TITLE
Logging mac-аddresses

### ISSUE THREAD

**Issue by marvinfisher9** [xdavidhu/mitmAP#28]
How do I find the logs of the mac-addresses of the connected devices, when sslstrip is enabled?

**Comment by hkessel1** [comment]
You can connect to the network and use a port scanner such as Fing, which is available on Android. Scan the network and you will have the mac's and IP's.

**Comment by xdavidhu** [comment]
You can also go into the screen session of hostapd, and look at the logs.

Enter screen session:
`screen -r mitmap-hostapd`
Turn on 'copy mode' to enable scrolling.
`CTRL + A + ESC`
Leave screen session:
`CTRL + A + D`

**Comment by marvinfisher9** [comment]
Thanks a lot!

**Comment by marvinfisher9** [comment]
Thanks a lot!
