### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DEVNULL'

### ISSUE THREAD

**Issue by yurifw** [xdavidhu/mitmAP#30]
`
[?] Install/Update dependencies? Y/n: n
[?] Please enter the name of your wireless interface (for the AP): wlan1
[?] Please enter the name of your internet connected interface: wlan1
[I] Backing up NetworkManager.cfg...
[I] Editing NetworkManager.cfg...
Traceback (most recent call last):
  File "mitmAP.py", line 62, in <module>
    write_file("/etc/NetworkManager/NetworkManager.conf", network_manager_cfg )
  File "mitmAP.py", line 29, in write_file
    _run_cmd_write((sudo, tee, path), s)
  File "mitmAP.py", line 22, in _run_cmd_write
    stdout=subprocess.DEVNULL, 
AttributeError: 'module' object has no attribute 'DEVNULL'

`
I'm getting this error after I input my interface's name, anyone know why?

**Comment by xdavidhu** [comment]
Hey,

Make sure to run mitmAP with Python 3.3 or newer.

**Comment by yurifw** [comment]
I tried with Python 2.7. I'll run it with Python 3, thanks :)
