### ISSUE TITLE
help

### ISSUE THREAD

**Issue by BlAd373** [xdavidhu/mitmAP#33]
Where do I find saved results?
2 Can I change the saved location?
3 how do I deauthentication a user
3 Can I save captured images with drifnet?

**Comment by xdavidhu** [comment]
Hey,
1 - The results are in the logs/ folder.
3 - You can change it in the code if you want but I wont recommend it.
3 - This is a fake AP tool, you cant deauth users with this. Try airoplay-ng for that.
4 - If you click on the image in driftnet, it will save it in your root directory.
