### ISSUE TITLE
unrecognized

### ISSUE THREAD

**Issue by balioas** [xdavidhu/mitmAP#34]
hello,
I need help : I am on virualbox, and when I start the fake AP, it write me that : 

[I] Restarting tail in 1 sec... (press 'CTRL + C' again to stop)
tail: unrecognized file system type 0x794c7630 for ‘/root/Desktop/mitmAP/logs/mitmap-sslstrip.log’. please report this to bug-coreutils@gnu.org. reverting to polling

what can I do ? thank you already ;)

**Comment by zerocolTHS** [comment]
I had the same issue but after i created the log file it seemed to be ok, not sure if that is the best fix but worked for me. 
nano /root/Desktop/mitmAP/logs/mitmap-sslstrip.log Then add a few spaces and save ?

**Comment by balioas** [comment]
Ok thank you !
I'll try it...

**Comment by balioas** [comment]
but what do you mean about few spaces ?

**Comment by zerocolTHS** [comment]
Press space bar so the file isn't empty ?

**Comment by balioas** [comment]
ok but after, what will I do to save ?

**Comment by zerocolTHS** [comment]
crtl + x  then y will save the file.

**Comment by balioas** [comment]
I know but what about the File Name to Write ?

**Comment by xdavidhu** [comment]
This is the file name: `mitmap-sslstrip.log`
