### ISSUE TITLE
README.md Snafu

### ISSUE THREAD

**Issue by brokenarrowsec** [xdavidhu/mitmAP#5]
Hey, just something that I noticed on your README.md that seemed to be incorrect. You state that, in order to run the python script, on Kali Linux, you have to use 'sudo,' well, that typically isn't the case. This is due to the fact that, by default, Kali boots into a user with 'root,' assuring that you never have to use 'sudo,' unless you are in another account. Just thought I should let you know, it's pretty minor...

**Comment by gsmnouri** [comment]
yes kali linux already rooted no need (sudo)

**Comment by xdavidhu** [comment]
Yes just you know, you cant lose anything with sudo, because there is a possibility that you are using kali with an other user instead of root.

So its really just to make sure.

**Comment by brokenarrowsec** [comment]
Alright, makes sense.
