### ISSUE TITLE
Airbase-ng instead of Hostapd

### ISSUE THREAD

**Issue by myst404** [xdavidhu/mitmAP#7]
Hello,

What about using Airbase-ng instead of Hostapd to create the AP?
The great thing about Airbase-ng is the -P option:
**-P : respond to all probes, even when specifying ESSIDs**
It can be combined with **-C** option.
Finally, it will perform channel hopping so that you do not have to fix a channel and all channels will be sprayed.

I do not think it is possible to do the same thing with Hostapd.

Also, just a small detail, Line 15:
`os.system("sudo chmod 777 " + script_path + "logs")`
755 permissions should work and be safer.

Regards,

**Comment by xdavidhu** [comment]
Closing the issue, but i will keep airbase-ng in mind.

**Comment by q2dg** [comment]
I think this issue should be open until the idea can be implemented or rejected formally

**Comment by zerocolTHS** [comment]
Sadly the author isn't checking his repos at the moment so this isn't likely to change any time soon.
